name: integration-tests

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: setup virtualenv
        run: |
          python -m venv env
          env/bin/pip install -r requirements.txt
        working-directory: ./

      - name: run unit tests
        run: |
          env/bin/python -m unittest discover
        working-directory: ./

      - name: run linter tests
        run: |
          env/bin/python -m flake8 --select F vantablack
        working-directory: ./

      - name: run mypy tests
        run: |
          env/bin/python -m mypy --check-untyped-defs --ignore-missing-imports vantablack
        working-directory: ./
