import pygame 

ANCHO = 1000
ALTO = 800
LIMITE_SUP = 30

COLOR_FONDO = "black"
COLOR_DEFENSOR = "red"
POS_X_DEFENSOR = ALTO - 75

TAM_FUENTE = 20

VIDAS = 5

ENEMIGOS_FPS = 32
TIEMPO_ENTRE_ENEMIGOS = 7000
COLOR_ENEMIGOS = "purple"

TIEMPO_ENTRE_BALAS = 200
BALA_ANCHO = 4
BALA_ALTO = 6
BALA_VELOCIDAD = 5
BALA_COLOR = "white"